python3 /home/ubuntu/Desktop/logi3_direct/titre/A.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AACG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AACI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AACIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AACIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AADI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAIC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAMC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAME.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAOI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAON.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAPL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAQC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AATC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AAWW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABBV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABCB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABCL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABCM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABEO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABEV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABMD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABOS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABSI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABUS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ABVC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACABU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAHU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAHW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAXR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAXU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACAXW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACEL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACER.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACET.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACEV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACEVU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACGL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACGLN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACGLO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACHC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACHL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACHR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACHV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACII.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACMR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACON.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACONW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACOR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACQR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACQRU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACTD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACVA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ACXP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADAG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADBE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADCT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADER.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADERW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADES.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADEX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADIL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADMA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADNT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADOC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADOCR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADOCW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADRA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADRT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADSE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADSEW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADSK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADTH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADTHW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADTN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADUS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADVM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ADXN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEFC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEIS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEMD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AENZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEPPZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AER.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AERC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AERI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AES.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AESC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AESC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEVA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AESE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEYE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AEZS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFACW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFAQU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFAQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFBI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFCG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFGB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFGC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFGD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFGE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFIB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFMD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFRM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AFYA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGBA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGBAR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGBAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGCB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGFS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGFY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGGR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGGRU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGIL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGILW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGLE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGMH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGNC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGNCM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGNCN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGNCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGNCP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGRI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGRIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGTC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGTI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AGYS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHPA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHPAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHPAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHPI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHRNU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AHT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIHS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIKI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIMAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIMC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AINC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AINV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIRTP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AIZN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AJG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AJRD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AJX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AJXA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKAM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKBA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKIC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKTS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKUS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AKYA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALBO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALCC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALDX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALEC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALEX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALFIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALGM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALGS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALGT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALHC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALIT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALJJ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALKS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALLY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALNA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALNY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALOR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALORU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALORW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALOT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALPA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALPAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALPN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALPP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALRM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALSA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALSAR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALSAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALSN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTUU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALTUW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALVR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALXO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALYA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ALZN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMAM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMAO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMAOW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMAT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMBA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMBC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMBO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMBP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMCI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMCIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMCR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMCX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AME.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMED.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMEH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMKR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMLX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMOT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMOV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPGW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMPY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMRC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMRK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMRX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMSC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMSF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMSWA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMTB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMTD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMTI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMWD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMWL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMYT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AMZN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANAB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANAT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANDE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANEB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANET.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANDE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANEB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANET.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGHW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANIK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANIX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANPC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANSS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANTE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANTM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANVS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANZU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANZUU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ANZUW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOGOW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOMR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AON.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AORT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOSL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AOUT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APACW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APAM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APCA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APCX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APCXW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APDN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APEI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APGB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/API.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APLD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APLE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APLS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APLT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APMI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APMIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APMIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APOG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APPF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APPH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APPHW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APPN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APRE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APRN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APSG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTMU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTMW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APVO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APWC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APXI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APXIU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APXIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/APYX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQMS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQNA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQNB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQNU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AQUA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARAV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARAY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBEW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBGU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBGW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARBK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCKU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCKW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARCT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARDC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARDS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARDX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AREB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AREBW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AREC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AREN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARES.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGUU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGUW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARGX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARHS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARIS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARIZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARIZR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARIZU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARIZW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARKO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARKOW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARKR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARLO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARLP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARMK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARMP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARNC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AROC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AROW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARQQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARQQW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARQT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARRW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARRWU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARRWW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARRY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTEW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTLW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTNA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARTW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARVL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARVN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARWR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARYD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ARYE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASAI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASAX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASCA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASCAR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASCBU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASGI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASIX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASLE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASLN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASMB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASML.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASND.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASNS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPAU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPAW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPCU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPCW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASPU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASRT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASRV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTLW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASTSW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASUR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASXC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASYS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ASZ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAKR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAKU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAKW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAQ.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATAX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATCOL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATCX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATEC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATEK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATEN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATER.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATEX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATGE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATHE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATHM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATHX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATIF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATKR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATLC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATLCL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATLCP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATLO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNFW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATOM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATOS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNFW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATOM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATOS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATRS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATSG.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATTO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATUS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATVC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATVCW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATVI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATXI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATXS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/ATY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUBAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUBN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUBN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUBAP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUDC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUGX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUID.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUMN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUPH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AURA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AURC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AURCU.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AURCW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUROW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUST.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUTL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUTO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUUD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUUDW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUVI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUVIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUVIP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AUY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVACW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVAH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVAL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVAN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVAV.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVB.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVCO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVCT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVCTW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVD.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVDL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVDX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVEO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVGO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVGOP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVGR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVHI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVHIW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVID.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVIR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVLR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVNS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVNT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVNW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVPT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVPTW.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVRO.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVT.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVTE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVTR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVTX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVXL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVY.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AVYA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWF.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWI.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWK.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWRE.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AWX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXAC.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXDX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXGN.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXH.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXL.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXLA.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXNX.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXON.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXP.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXR.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXS.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/AXSM.py &
python3 /home/ubuntu/Desktop/logi3_direct/titre/%launcher%.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &.py &
